## YAML Template.
admin_login:
    path: /login/admin
    defaults: { _controller: 'AdminController::connexion' }
admin_logout:
    path: /admin/deconnexion
    defaults: { _controller: 'AdminController::deconnexion' }
admin_home:
    path: /admin
    defaults: { _controller: 'AdminController::index' }
admin_profil:
    path: /admin/profile
    defaults: { _controller: 'AdminController::profil' }