## YAML Template.
home:
    path: /
    defaults: { _controller: 'FrontController::index' }
    
front_ajax_information_pays:
    pattern: /ajax-get-information-pays
    defaults: { _controller: 'FrontController::ajaxInformationFromPays' }
    requirements:
      _method: POST

front_ajax_information_camp:
    pattern: /ajax-get-information-camp
    defaults: { _controller: 'FrontController::ajaxInformationFromCamp' }
    requirements:
      _method: POST